version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: credore-ecommerce
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - redis
      - db

  redis:
    image: redis:7.2.3
    container_name: redis-farmshop
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - cache:/data/cache

  db:
    image: postgres:13
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12asdf34
      POSTGRES_DB: ecommerce
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  cache:
    driver: local
